env:
  dtype: bfloat16 # will be converted to th.dtype
  device: cuda
  hf_cache_dir: models # resolves to root.parent/hf_cache_dir
  texts_dir: data/texts
  tokens_dir: data/tokens
  activations_dir: data/activations
  debug: False

llm:
  hf_name: allenai/Olmo-3-1125-32B
  layer_idx: 15
  batch_size: 100

  sequence_aggregation_method: final # max, sum, final

data:
  name: days_filtered

filter:
  corpus: HuggingFaceFW/fineweb
  regex_file: days
  num_occurences: 20