defaults:
  - llm: gpt2
  - data: days
  - sae: llama3.1-8b-base_temporal
  - filter: days_fineweb
  - exp: final
  - _self_

env:
  dtype: bfloat16 # will be converted to th.dtype
  device: cuda
  hf_cache_dir: models # resolves to root.parent/hf_cache_dir
  texts_dir: data/texts
  tokens_dir: data/tokens
  activations_dir: data/activations
  sae_dir: data/trained_saes
  debug: False

data:
  name: days_filtered
  fixed_context_length: 3

